<!-- Release Info -->
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 3.2.1-DEV<span class="float-end">2023-06-..</span></div>
    <div class="card-body">
        <h6>Bugfix</h6>
        <ul>
            <li>User with ID 1 (admin) cannot be deactivated or banned</li>
        </ul>
        <h6>Improvement</h6>
        <ul>
            <li>Added CI4-Auth toi CodeIgniter development toolbar</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 3.2.0<span class="float-end">2023-06-03</span></div>
    <div class="card-body">
        <h6>Bugfix</h6>
        <ul>
            <li>Fixed vulnerability as documented here: <a href="https://github.com/advisories/GHSA-m6m8-6gq8-c9fj"> CVE-2023-32692</a></li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 3.1.2<span class="float-end">2023-06-02</span></div>
    <div class="card-body">
        <h6>Bugfix</h6>
        <ul>
            <li>Fixed validation rule for permission names (only lower alpha characters and dots)</li>
            <li>Fixed ban switch on user edit page</li>
            <li>Removed extra slash from navbar links</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 3.1.1<span class="float-end">2023-05-15</span></div>
    <div class="card-body">
        <h6>Bugfix</h6>
        <ul>
            <li>Fixed navbar not opening in responsive mode</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 3.1.0<span class="float-end">2023-05-12</span></div>
    <div class="card-body">
        <h6>Improvement</h6>
        <ul>
            <li>Permissions renamed to a more proper naming convention</li>
            <li>Permissions to manage permissions are not given to any user when installing. They can be given to any user, group or role via the GUI after.</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 3.0.0<span class="float-end">2023-05-08</span></div>
    <div class="card-body">
        <h6>Feature</h6>
        <ul>
            <li>Two factor authentication (2FA)</li>
            <li>About page (incl. release info)</li>
            <li>Icon PNGs</li>
        </ul>
        <h6>Improvement</h6>
        <ul>
            <li>Permissions display on Groups page</li>
            <li>Permissions display on Roles page</li>
            <li>Account status icons Users page</li>
            <li>Split readme file for better usability</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 2.1.0<span class="float-end">2023-05-04</span></div>
    <div class="card-body">
        <h6>Improvement</h6>
        <ul>
            <li>Switch to Bootstrap Icons</li>
            <li>WhoAmI page</li>
            <li>Layout adjustments</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 2.0.0<span class="float-end">2023-05-01</span></div>
    <div class="card-body">
        <h6>Improvement</h6>
        <ul>
            <li>Update to Codeigniter 4.3.3</li>
            <li>Update to Bootstrap 5.2.3</li>
            <li>Update to Font Awesome 6.4.0</li>
            <li>Complete database seeds (to run a test)</li>
            <li>Code maintenance and minor bug fixes</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.5.0<span class="float-end">2022-05-10</span></div>
    <div class="card-body">
        <h6>Feature</h6>
        <ul>
            <li>Added a stub for the UsersOptions table</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.4.0<span class="float-end">2022-03-25</span></div>
    <div class="card-body">
        <h6>Feature</h6>
        <ul>
            <li>The user account edit page now contains a switch to activate or deactivate a user.</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.3.2<span class="float-end">2022-03-23</span></div>
    <div class="card-body">
        <h6>Bugfix</h6>
        <ul>
            <li>Fixed the Register dialog which was expecting firstname, lastname and displayname. Added as hidden empty input fields.</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.3.1<span class="float-end">2022-03-22</span></div>
    <div class="card-body">
        <h6>Bugfix</h6>
        <ul>
            <li>Reset password form validation did not work. Added a workaround</li>
            <li>Bugfix in removePermissionFromGroup</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.3.0<span class="float-end">2022-03-19</span></div>
    <div class="card-body">
        <h6>Feature</h6>
        <ul>
            <li>Added Spanish language (contribution)</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.2.2<span class="float-end">2022-03-19</span></div>
    <div class="card-body">
        <h6>Bugfix</h6>
        <ul>
            <li>Fixed reset hash creation on user create (when Reset Mail selected so in front end)</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.2.1<span class="float-end">2022-03-09</span></div>
    <div class="card-body">
        <h6>Improvement</h6>
        <ul>
            <li>A password reset email is now optional (checkbox) on the user creation form.</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.2.0<span class="float-end">2022-03-08</span></div>
    <div class="card-body">
        <h6>Feature</h6>
        <ul>
            <li>Added sendPasswordResetUponCreate feature</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.1.0<span class="float-end">2022-02-27</span></div>
    <div class="card-body">
        <h6>Bugfix</h6>
        <ul>
            <li>Several bug fixes</li>
        </ul>
        <h6>Improvement</h6>
        <ul>
            <li>Added support for custom config settings to be passed to the views.</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.0.0<span class="float-end">2022-01-15</span></div>
    <div class="card-body">
        <h6>Improvement</h6>
        <ul>
            <li>Layout fixes</li>
        </ul>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header"><i class="bi-box me-3"></i>Release 1.0.0-beta<span class="float-end">2022-01-05</span></div>
    <div class="card-body">
        <p>First beta release</p>
    </div>
</div>
<div class="spacer-20"></div>
